// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRkxzgRKqBxObjgSCx6MWSrCHLvQg71zw',
    appId: '1:268776385890:web:0fcc91f16819586321103b',
    messagingSenderId: '268776385890',
    projectId: 'e-commerce-app-22927',
    authDomain: 'e-commerce-app-22927.firebaseapp.com',
    storageBucket: 'e-commerce-app-22927.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAcT3d-hnssP5Zkj9uEVCLQ27N19yTAzk',
    appId: '1:268776385890:android:76ec196a2f55c3f521103b',
    messagingSenderId: '268776385890',
    projectId: 'e-commerce-app-22927',
    storageBucket: 'e-commerce-app-22927.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv8NNiQeP9CwtetyCtncBlSCjIm_S1VKw',
    appId: '1:268776385890:ios:f0261b8e9a0f835321103b',
    messagingSenderId: '268776385890',
    projectId: 'e-commerce-app-22927',
    storageBucket: 'e-commerce-app-22927.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv8NNiQeP9CwtetyCtncBlSCjIm_S1VKw',
    appId: '1:268776385890:ios:f0261b8e9a0f835321103b',
    messagingSenderId: '268776385890',
    projectId: 'e-commerce-app-22927',
    storageBucket: 'e-commerce-app-22927.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRkxzgRKqBxObjgSCx6MWSrCHLvQg71zw',
    appId: '1:268776385890:web:0fcc91f16819586321103b',
    messagingSenderId: '268776385890',
    projectId: 'e-commerce-app-22927',
    authDomain: 'e-commerce-app-22927.firebaseapp.com',
    storageBucket: 'e-commerce-app-22927.firebasestorage.app',
  );
}
